### ISSUE TITLE
Template-paths not resolved correctly, if they do not lie in root.

### ISSUE THREAD

**Issue by Codeschmied** [chunksnbits/grunt-template-render#2]
Example:
The project root is C:\code\production\prototype
The template file is C:\code\production\prototype\app\mytemplate.html
If you now try to reference the template file like this:  <%= render('//app//mytemplate.html') %>
you get this error:
Warning: Source file `C:\code\production\prototypeundefined` not found.

**Comment by chunksnbits** [comment]
Hi, looks odd. 

Have you tried setting the cwd option (https://github.com/chunksnbits/grunt-template-render#cwd)?

**Comment by Codeschmied** [comment]
Hi! Thanks for the quick answer. 
This solves this problem. I now have another problem now. I will post it in a new issue.
